ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE mark ADD CONSTRAINT CHK_ColumnD_DocExc CHECK (mark>0 and mark<=10);
ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL, ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE subject ADD CONSTRAINT CHK_ColumnD CHECK (grade>0 and grade<=5);
ALTER TABLE paymentType ADD CONSTRAINT constraint_name UNIQUE (name);
ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment ALTER COLUMN amount decimal NOT NULL;
ALTER TABLE payment ALTER COLUMN payment_date DateTime NOT NULL;